### ISSUE TITLE
Allow editing of cif files in app

### ISSUE THREAD

**Issue by AndrewSazonov** [easyDiffraction/easyDiffraction#59]
- [x] Front-end implementation (Project page, similar to Sample/Experiment page)
- [x] Back-end implementation (With ability to edit project name and keywords)

**Comment by wardsimon** [comment]
- [ ] Add Main.cif Edit tab to Project page
- - [x] Front-end implementation (Project page, similar to Sample/Experiment page)
- - [ ] Back-end implementation (With ability to edit project name and keywords)
- [x] Make the sample and experiment cif view editable #52 
- - [x] Front-end implementation (Sample/Experiment page, updates etc)
- - [x] Back-end implementation (Link to easyInterface)

**Comment by wardsimon** [comment]
Addressed in #63
